// @generated by tools/gen-schema.mjs from params/**/*.toml and schema/protocol.toml. Do not edit.

use crate::params::{Curve, ParamInfo};

pub const COUNT: usize = 43;

pub const ENV_ATTACK: [u16; 4] = [0, 5, 10, 15];
pub const ENV_HOLD: [u16; 4] = [1, 6, 11, 16];
pub const ENV_DECAY: [u16; 4] = [2, 7, 12, 17];
pub const ENV_SUSTAIN: [u16; 4] = [3, 8, 13, 18];
pub const ENV_RELEASE: [u16; 4] = [4, 9, 14, 19];
pub const MASTER_VOLUME: u16 = 20;
pub const OSC_ENABLE: [u16; 3] = [21, 28, 35];
pub const OSC_LEVEL: [u16; 3] = [22, 29, 36];
pub const OSC_PAN: [u16; 3] = [23, 30, 37];
pub const OSC_OCTAVE: [u16; 3] = [24, 31, 38];
pub const OSC_SEMI: [u16; 3] = [25, 32, 39];
pub const OSC_FINE: [u16; 3] = [26, 33, 40];
pub const OSC_COARSE: [u16; 3] = [27, 34, 41];
pub const VOICE_POLYPHONY: u16 = 42;

pub static INFO: [ParamInfo; COUNT] = [
    ParamInfo { key: "env.1.attack", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.025, flags: 1 },
    ParamInfo { key: "env.1.hold", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.0, flags: 1 },
    ParamInfo { key: "env.1.decay", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.31498027, flags: 1 },
    ParamInfo { key: "env.1.sustain", curve: Curve::Lin, min: 0.0, max: 1.0, default: 1.0, flags: 1 },
    ParamInfo { key: "env.1.release", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.07768081, flags: 1 },
    ParamInfo { key: "env.2.attack", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.025, flags: 1 },
    ParamInfo { key: "env.2.hold", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.0, flags: 1 },
    ParamInfo { key: "env.2.decay", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.31498027, flags: 1 },
    ParamInfo { key: "env.2.sustain", curve: Curve::Lin, min: 0.0, max: 1.0, default: 1.0, flags: 1 },
    ParamInfo { key: "env.2.release", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.07768081, flags: 1 },
    ParamInfo { key: "env.3.attack", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.025, flags: 1 },
    ParamInfo { key: "env.3.hold", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.0, flags: 1 },
    ParamInfo { key: "env.3.decay", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.31498027, flags: 1 },
    ParamInfo { key: "env.3.sustain", curve: Curve::Lin, min: 0.0, max: 1.0, default: 1.0, flags: 1 },
    ParamInfo { key: "env.3.release", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.07768081, flags: 1 },
    ParamInfo { key: "env.4.attack", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.025, flags: 1 },
    ParamInfo { key: "env.4.hold", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.0, flags: 1 },
    ParamInfo { key: "env.4.decay", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.31498027, flags: 1 },
    ParamInfo { key: "env.4.sustain", curve: Curve::Lin, min: 0.0, max: 1.0, default: 1.0, flags: 1 },
    ParamInfo { key: "env.4.release", curve: Curve::Pow(3.0), min: 0.0, max: 32000.0, default: 0.07768081, flags: 1 },
    ParamInfo { key: "master.volume", curve: Curve::Db, min: -60.0, max: 6.0, default: 0.8181818, flags: 2 },
    ParamInfo { key: "osc.a.enable", curve: Curve::Bool, min: 0.0, max: 1.0, default: 1.0, flags: 0 },
    ParamInfo { key: "osc.a.level", curve: Curve::Lin, min: 0.0, max: 1.0, default: 0.75, flags: 3 },
    ParamInfo { key: "osc.a.pan", curve: Curve::Lin, min: -1.0, max: 1.0, default: 0.5, flags: 3 },
    ParamInfo { key: "osc.a.octave", curve: Curve::Int, min: -4.0, max: 4.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.a.semi", curve: Curve::Int, min: -12.0, max: 12.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.a.fine", curve: Curve::Lin, min: -100.0, max: 100.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.a.coarse", curve: Curve::Lin, min: -48.0, max: 48.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.b.enable", curve: Curve::Bool, min: 0.0, max: 1.0, default: 0.0, flags: 0 },
    ParamInfo { key: "osc.b.level", curve: Curve::Lin, min: 0.0, max: 1.0, default: 0.75, flags: 3 },
    ParamInfo { key: "osc.b.pan", curve: Curve::Lin, min: -1.0, max: 1.0, default: 0.5, flags: 3 },
    ParamInfo { key: "osc.b.octave", curve: Curve::Int, min: -4.0, max: 4.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.b.semi", curve: Curve::Int, min: -12.0, max: 12.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.b.fine", curve: Curve::Lin, min: -100.0, max: 100.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.b.coarse", curve: Curve::Lin, min: -48.0, max: 48.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.c.enable", curve: Curve::Bool, min: 0.0, max: 1.0, default: 0.0, flags: 0 },
    ParamInfo { key: "osc.c.level", curve: Curve::Lin, min: 0.0, max: 1.0, default: 0.75, flags: 3 },
    ParamInfo { key: "osc.c.pan", curve: Curve::Lin, min: -1.0, max: 1.0, default: 0.5, flags: 3 },
    ParamInfo { key: "osc.c.octave", curve: Curve::Int, min: -4.0, max: 4.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.c.semi", curve: Curve::Int, min: -12.0, max: 12.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.c.fine", curve: Curve::Lin, min: -100.0, max: 100.0, default: 0.5, flags: 1 },
    ParamInfo { key: "osc.c.coarse", curve: Curve::Lin, min: -48.0, max: 48.0, default: 0.5, flags: 1 },
    ParamInfo { key: "voice.polyphony", curve: Curve::Int, min: 1.0, max: 32.0, default: 0.22580644, flags: 0 },
];
