// @generated by tools/gen-schema.mjs from params/**/*.toml and schema/protocol.toml. Do not edit.

pub const ABI_HASH: u32 = 0x01e0bb4b;
pub const HEADER_BYTES: usize = 16;
pub const MAX_VOICES: usize = 32;
pub const VOICE_SLOTS: usize = 40;
pub const SUB_BLOCK: usize = 16;
pub const MAX_BLOCK: usize = 2048;
pub const CMD_CAPACITY: usize = 262144;
pub const MAX_UNISON: usize = 16;
pub const MAX_MOD_SLOTS: usize = 64;
pub const MAX_FRAMES: usize = 256;
pub const FRAME_LEN: usize = 2048;
pub const FRAME_STRIDE: usize = 9227;
pub const OSC_COUNT: usize = 3;
pub const MAX_GRAINS: usize = 512;
pub const MAX_ZONES: usize = 128;
pub const SAMPLE_LEVELS: usize = 6;
pub const SPEC_SIZE: usize = 2048;
pub const SPEC_HOP: usize = 512;
pub const SPEC_PRE: usize = 2;
pub const SPEC_FILTER_POINTS: usize = 64;
pub const ARP_STEPS: usize = 16;
pub const ARP_BANKS: usize = 12;
pub const ARP_LANES: usize = 7;
pub const CLIP_SLOTS: usize = 12;
pub const CLIP_NOTES: usize = 512;
pub const CLIP_LANES: usize = 4;
pub const CLIP_POINTS: usize = 64;

pub mod op {
    pub const SET_PARAM: u16 = 1;
    pub const NOTE_ON: u16 = 2;
    pub const NOTE_OFF: u16 = 3;
    pub const ALL_NOTES_OFF: u16 = 4;
    pub const ALL_SOUND_OFF: u16 = 5;
    pub const PITCH_BEND: u16 = 6;
    pub const CONTROLLER: u16 = 7;
    pub const CHANNEL_PRESSURE: u16 = 8;
    pub const POLY_PRESSURE: u16 = 9;
    pub const SET_TAPS: u16 = 16;
    pub const RESET: u16 = 17;
    pub const LOAD_TABLE: u16 = 20;
    pub const UPDATE_FRAME: u16 = 21;
    pub const RESET_TABLE: u16 = 22;
    pub const SET_MOD_SLOT: u16 = 24;
    pub const SET_LFO_SHAPE: u16 = 26;
    pub const LOAD_SAMPLE: u16 = 27;
    pub const SET_OSC_CURVE: u16 = 28;
    pub const SET_CHAIN: u16 = 29;
    pub const LOAD_IR: u16 = 30;
    pub const SET_TUNING: u16 = 32;
    pub const LOAD_OSC_SAMPLE: u16 = 33;
    pub const LOAD_MULTI: u16 = 34;
    pub const LOAD_SPECTRAL: u16 = 35;
    pub const SET_SPECTRAL_FILTER: u16 = 36;
    pub const TRANSPORT: u16 = 37;
    pub const SET_ARP_PATTERN: u16 = 38;
    pub const SET_CLIP: u16 = 39;
    pub const SET_CLIP_LANE: u16 = 40;
    pub const CLEAR_MOD: u16 = 25;
    pub const DEBUG: u16 = 31;
}

pub mod bytes {
    pub const SET_PARAM: usize = 8;
    pub const NOTE_ON: usize = 16;
    pub const NOTE_OFF: usize = 16;
    pub const ALL_NOTES_OFF: usize = 0;
    pub const ALL_SOUND_OFF: usize = 0;
    pub const PITCH_BEND: usize = 8;
    pub const CONTROLLER: usize = 8;
    pub const CHANNEL_PRESSURE: usize = 8;
    pub const POLY_PRESSURE: usize = 16;
    pub const SET_TAPS: usize = 8;
    pub const RESET: usize = 0;
    pub const LOAD_TABLE: usize = 16;
    pub const UPDATE_FRAME: usize = 16;
    pub const RESET_TABLE: usize = 8;
    pub const SET_MOD_SLOT: usize = 24;
    pub const SET_LFO_SHAPE: usize = 8;
    pub const LOAD_SAMPLE: usize = 24;
    pub const SET_OSC_CURVE: usize = 8;
    pub const SET_CHAIN: usize = 8;
    pub const LOAD_IR: usize = 16;
    pub const SET_TUNING: usize = 8;
    pub const LOAD_OSC_SAMPLE: usize = 24;
    pub const LOAD_MULTI: usize = 16;
    pub const LOAD_SPECTRAL: usize = 24;
    pub const SET_SPECTRAL_FILTER: usize = 8;
    pub const TRANSPORT: usize = 8;
    pub const SET_ARP_PATTERN: usize = 8;
    pub const SET_CLIP: usize = 8;
    pub const SET_CLIP_LANE: usize = 8;
    pub const CLEAR_MOD: usize = 0;
    pub const DEBUG: usize = 8;
}

/// Where the variable-length tail starts in the payload, for commands that have one.
pub fn tail_offset(op: u16) -> Option<usize> {
    match op {
        op::SET_LFO_SHAPE => Some(8),
        op::SET_OSC_CURVE => Some(8),
        op::SET_CHAIN => Some(8),
        op::SET_TUNING => Some(8),
        op::SET_SPECTRAL_FILTER => Some(8),
        op::SET_ARP_PATTERN => Some(8),
        op::SET_CLIP => Some(8),
        op::SET_CLIP_LANE => Some(8),
        _ => None,
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Command {
    /// Set a parameter to a normalized value in 0..1.
    SetParam { id: u16, value: f32 },
    /// Start a note. noteId is chosen by the host and matched by NoteOff.
    NoteOn { note: u8, channel: u8, velocity: f32, note_id: u32 },
    /// Release a note: by noteId when it's non-zero, else by note and channel.
    NoteOff { note: u8, channel: u8, velocity: f32, note_id: u32 },
    /// Release every voice (MIDI CC 123).
    AllNotesOff,
    /// Fade every voice out within a few milliseconds (MIDI CC 120).
    AllSoundOff,
    /// Pitch wheel position, -1..1.
    PitchBend { channel: u8, value: f32 },
    /// A MIDI continuous controller, value 0..1.
    Controller { channel: u8, cc: u8, value: f32 },
    /// Channel aftertouch, 0..1.
    ChannelPressure { channel: u8, value: f32 },
    /// Per-note aftertouch, 0..1.
    PolyPressure { note: u8, channel: u8, value: f32, note_id: u32 },
    /// Choose which taps the engine records (bit i = tap i).
    SetTaps { mask: u32 },
    /// Clear all DSP state (voices, smoothers, tails) but keep parameters.
    Reset,
    /// Give an oscillator a wavetable: `bytes` of mip-mapped frames at `ptr` (from wt_asset_alloc). The engine takes ownership.
    LoadTable { osc: u8, frames: u16, ptr: u32, bytes: u32 },
    /// Overwrite one mip-mapped frame of an oscillator's table from an asset; the engine frees the asset.
    UpdateFrame { osc: u8, index: u16, ptr: u32, bytes: u32 },
    /// Return an oscillator to the built-in saw.
    ResetTable { osc: u8 },
    /// Configure one modulation matrix slot. flags: bit 0 bipolar, bit 1 bypass. source 0 clears the slot. curve bends the source (-1..1); output scales the result.
    SetModSlot { slot: u8, source: u8, aux: u8, flags: u8, dest: u16, amount: f32, curve: f32, output: f32 },
    /// An LFO's drawn shape (kind 0: points x, y, curve with x in 0..1 and y in -1..1) or path (kind 1: points x, y, curve in the XY plane). count points follow, three f32 each.
    SetLfoShape { lfo: u8, kind: u8, count: u16 },
    /// Give a sample slot (0: noise) mono f32 audio at ptr (from wt_asset_alloc) recorded at `rate` Hz. The engine takes ownership.
    LoadSample { slot: u8, frames: u32, rate: f32, ptr: u32, bytes: u32 },
    /// An oscillator's drawn remap curve (warps Remap 1-4), as a lookup table: count values in 0..1 over x from 0 to 1 (257 for full detail).
    SetOscCurve { osc: u8, count: u16 },
    /// An FX chain's modules, in order: chain 0 is the Main rack, 1 Bus 1, 2 Bus 2, and 3 + 3 × splitter + band the band chains of the splitters. Each entry is type × 256 + instance (types in fx/mod.rs order).
    SetChain { chain: u8, count: u8 },
    /// Give convolver `inst` an impulse response prepared by the tools (layout in crates/engine/src/fx/convolve.rs) at ptr (from wt_asset_alloc). taps = 0 removes it. The engine takes ownership.
    LoadIr { inst: u8, taps: u32, ptr: u32, bytes: u32 },
    /// The pitch of every MIDI note, as a fractional note number (count values, 128 for all; 12-TET is n → n). Scala, KBM and TUN files are turned into this by the host.
    SetTuning { count: u16 },
    /// Give an oscillator the recording its Sample and Granular types play: `levels` copies (full rate, then each half the length, low-passed), each `channels` planar runs of that level's frames, then `slices` f32 slice starts in frames. ptr from wt_asset_alloc (0 removes it); the engine takes ownership.
    LoadOscSample { osc: u8, channels: u8, levels: u8, slices: u16, frames: u32, rate: f32, ptr: u32, bytes: u32 },
    /// Give an oscillator a multisample: `zones` zone headers of 16 f32 (see crates/engine/src/osc/multi.rs), then the zones' audio. ptr from wt_asset_alloc (0 removes it); the engine takes ownership.
    LoadMulti { osc: u8, zones: u16, ptr: u32, bytes: u32 },
    /// Give an oscillator the spectral analysis its Spectral type plays: `frames` frames of specSize/2+1 magnitudes, as many phases and a transient flag, the first specPre of them before time 0; hop specHop at `rate`. ptr from wt_asset_alloc (0 removes it); the engine takes ownership.
    LoadSpectral { osc: u8, frames: u32, rate: f32, ptr: u32, bytes: u32 },
    /// The drawn spectral filter of an oscillator: `count` gains (0..1) spread evenly over log frequency from 20 Hz to 20 kHz.
    SetSpectralFilter { osc: u8, count: u16 },
    /// Start (1) or stop (0) the transport: clips play while it runs, and the tempo grid restarts at beat 0 on a start.
    Transport { play: u8 },
    /// An arpeggiator pattern: `count` floats, arpLanes lanes of arpSteps (on, gate, velocity, chance, bend in semitones, strum, degree).
    SetArpPattern { bank: u8, count: u16 },
    /// A clip's notes: `count` × 6 floats (start and length in beats, key, velocity, chance, bend in semitones), in start order, and its length in beats.
    SetClip { slot: u8, count: u16, length: f32 },
    /// One of a clip's automation lanes: parameter `param` (0xFFFF: none) at `count` points of (beat, normalized value).
    SetClipLane { slot: u8, lane: u8, param: u16, count: u16 },
    /// Clear every modulation slot.
    ClearMod,
    /// Test hooks; see [debug].
    Debug { code: u32, arg: f32 },
}

/// Decode one payload. Returns None for unknown ops or short payloads.
pub fn decode(op: u16, p: &[u8]) -> Option<Command> {
    match op {
        op::SET_PARAM if p.len() >= 8 => Some(Command::SetParam { id: rd_u16(p, 0), value: rd_f32(p, 4) }),
        op::NOTE_ON if p.len() >= 12 => Some(Command::NoteOn { note: rd_u8(p, 0), channel: rd_u8(p, 1), velocity: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::NOTE_OFF if p.len() >= 12 => Some(Command::NoteOff { note: rd_u8(p, 0), channel: rd_u8(p, 1), velocity: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::ALL_NOTES_OFF => Some(Command::AllNotesOff),
        op::ALL_SOUND_OFF => Some(Command::AllSoundOff),
        op::PITCH_BEND if p.len() >= 8 => Some(Command::PitchBend { channel: rd_u8(p, 0), value: rd_f32(p, 4) }),
        op::CONTROLLER if p.len() >= 8 => Some(Command::Controller { channel: rd_u8(p, 0), cc: rd_u8(p, 1), value: rd_f32(p, 4) }),
        op::CHANNEL_PRESSURE if p.len() >= 8 => Some(Command::ChannelPressure { channel: rd_u8(p, 0), value: rd_f32(p, 4) }),
        op::POLY_PRESSURE if p.len() >= 12 => Some(Command::PolyPressure { note: rd_u8(p, 0), channel: rd_u8(p, 1), value: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::SET_TAPS if p.len() >= 4 => Some(Command::SetTaps { mask: rd_u32(p, 0) }),
        op::RESET => Some(Command::Reset),
        op::LOAD_TABLE if p.len() >= 12 => Some(Command::LoadTable { osc: rd_u8(p, 0), frames: rd_u16(p, 2), ptr: rd_u32(p, 4), bytes: rd_u32(p, 8) }),
        op::UPDATE_FRAME if p.len() >= 12 => Some(Command::UpdateFrame { osc: rd_u8(p, 0), index: rd_u16(p, 2), ptr: rd_u32(p, 4), bytes: rd_u32(p, 8) }),
        op::RESET_TABLE if !p.is_empty() => Some(Command::ResetTable { osc: rd_u8(p, 0) }),
        op::SET_MOD_SLOT if p.len() >= 20 => Some(Command::SetModSlot { slot: rd_u8(p, 0), source: rd_u8(p, 1), aux: rd_u8(p, 2), flags: rd_u8(p, 3), dest: rd_u16(p, 4), amount: rd_f32(p, 8), curve: rd_f32(p, 12), output: rd_f32(p, 16) }),
        op::SET_LFO_SHAPE if p.len() >= 4 => Some(Command::SetLfoShape { lfo: rd_u8(p, 0), kind: rd_u8(p, 1), count: rd_u16(p, 2) }),
        op::LOAD_SAMPLE if p.len() >= 20 => Some(Command::LoadSample { slot: rd_u8(p, 0), frames: rd_u32(p, 4), rate: rd_f32(p, 8), ptr: rd_u32(p, 12), bytes: rd_u32(p, 16) }),
        op::SET_OSC_CURVE if p.len() >= 4 => Some(Command::SetOscCurve { osc: rd_u8(p, 0), count: rd_u16(p, 2) }),
        op::SET_CHAIN if p.len() >= 2 => Some(Command::SetChain { chain: rd_u8(p, 0), count: rd_u8(p, 1) }),
        op::LOAD_IR if p.len() >= 16 => Some(Command::LoadIr { inst: rd_u8(p, 0), taps: rd_u32(p, 4), ptr: rd_u32(p, 8), bytes: rd_u32(p, 12) }),
        op::SET_TUNING if p.len() >= 2 => Some(Command::SetTuning { count: rd_u16(p, 0) }),
        op::LOAD_OSC_SAMPLE if p.len() >= 24 => Some(Command::LoadOscSample { osc: rd_u8(p, 0), channels: rd_u8(p, 1), levels: rd_u8(p, 2), slices: rd_u16(p, 4), frames: rd_u32(p, 8), rate: rd_f32(p, 12), ptr: rd_u32(p, 16), bytes: rd_u32(p, 20) }),
        op::LOAD_MULTI if p.len() >= 12 => Some(Command::LoadMulti { osc: rd_u8(p, 0), zones: rd_u16(p, 2), ptr: rd_u32(p, 4), bytes: rd_u32(p, 8) }),
        op::LOAD_SPECTRAL if p.len() >= 20 => Some(Command::LoadSpectral { osc: rd_u8(p, 0), frames: rd_u32(p, 4), rate: rd_f32(p, 8), ptr: rd_u32(p, 12), bytes: rd_u32(p, 16) }),
        op::SET_SPECTRAL_FILTER if p.len() >= 4 => Some(Command::SetSpectralFilter { osc: rd_u8(p, 0), count: rd_u16(p, 2) }),
        op::TRANSPORT if !p.is_empty() => Some(Command::Transport { play: rd_u8(p, 0) }),
        op::SET_ARP_PATTERN if p.len() >= 4 => Some(Command::SetArpPattern { bank: rd_u8(p, 0), count: rd_u16(p, 2) }),
        op::SET_CLIP if p.len() >= 8 => Some(Command::SetClip { slot: rd_u8(p, 0), count: rd_u16(p, 2), length: rd_f32(p, 4) }),
        op::SET_CLIP_LANE if p.len() >= 6 => Some(Command::SetClipLane { slot: rd_u8(p, 0), lane: rd_u8(p, 1), param: rd_u16(p, 2), count: rd_u16(p, 4) }),
        op::CLEAR_MOD => Some(Command::ClearMod),
        op::DEBUG if p.len() >= 8 => Some(Command::Debug { code: rd_u32(p, 0), arg: rd_f32(p, 4) }),
        _ => None,
    }
}

#[inline]
fn rd_u8(p: &[u8], o: usize) -> u8 {
    p[o]
}
#[inline]
fn rd_u16(p: &[u8], o: usize) -> u16 {
    let mut b = [0u8; 2];
    b.copy_from_slice(&p[o..o + 2]);
    u16::from_le_bytes(b)
}
#[inline]
fn rd_u32(p: &[u8], o: usize) -> u32 {
    let mut b = [0u8; 4];
    b.copy_from_slice(&p[o..o + 4]);
    u32::from_le_bytes(b)
}
#[inline]
fn rd_f32(p: &[u8], o: usize) -> f32 {
    let mut b = [0u8; 4];
    b.copy_from_slice(&p[o..o + 4]);
    f32::from_le_bytes(b)
}

pub mod debug {
    pub const TRAP: u32 = 1;
    pub const SCALAR: u32 = 2;
    pub const NO_BANDLIMIT: u32 = 3;
}

/// Telemetry slot offsets (f32 each).
pub mod tel {
    pub const VOICES_ACTIVE: usize = 0;
    pub const PEAK_L: usize = 1;
    pub const PEAK_R: usize = 2;
    pub const FOCUS_VOICE: usize = 3;
    pub const QUEUE_DROPS: usize = 4;
    pub const UNKNOWN_CMDS: usize = 5;
    pub const VOICE_NOTE: usize = 6;
    pub const VOICE_NOTE_LEN: usize = 40;
    pub const VOICE_LEVEL: usize = 46;
    pub const VOICE_LEVEL_LEN: usize = 40;
    pub const OSC_WT_POS: usize = 86;
    pub const OSC_WT_POS_LEN: usize = 3;
    pub const OSC_FRAMES: usize = 89;
    pub const OSC_FRAMES_LEN: usize = 3;
    pub const TABLE_ERRORS: usize = 92;
    pub const FOCUS_PITCH: usize = 93;
    pub const FOCUS_ENV: usize = 94;
    pub const FOCUS_ENV_LEN: usize = 4;
    pub const FOCUS_CUTOFF: usize = 98;
    pub const MOD_SLOTS: usize = 99;
    pub const MOD_DEST: usize = 100;
    pub const MOD_DEST_LEN: usize = 64;
    pub const MOD_VALUE: usize = 164;
    pub const MOD_VALUE_LEN: usize = 64;
    pub const LFO_VALUE: usize = 228;
    pub const LFO_VALUE_LEN: usize = 10;
    pub const LFO_Y: usize = 238;
    pub const LFO_Y_LEN: usize = 10;
    pub const LFO_PHASE: usize = 248;
    pub const LFO_PHASE_LEN: usize = 10;
    pub const MACRO_VALUE: usize = 258;
    pub const MACRO_VALUE_LEN: usize = 8;
    pub const OVERSAMPLE: usize = 266;
    pub const FX_GR: usize = 267;
    pub const FX_GR_LEN: usize = 12;
    pub const FX_IR: usize = 279;
    pub const FX_IR_LEN: usize = 4;
    pub const OSC_PLAY: usize = 283;
    pub const OSC_PLAY_LEN: usize = 3;
    pub const GRAINS: usize = 286;
    pub const GRAINS_STOLEN: usize = 287;
    pub const OSC_ASSETS: usize = 288;
    pub const OSC_ASSETS_LEN: usize = 9;
    pub const PLAYING: usize = 297;
    pub const BEAT: usize = 298;
    pub const ARP_STEP: usize = 299;
    pub const CLIP_PLAYING: usize = 300;
    pub const CLIP_POS: usize = 301;
    pub const SEQ_NOTES: usize = 302;
    pub const LEN: usize = 303;
}

pub mod tap {
    pub const MASTER_L: usize = 0;
    pub const MASTER_R: usize = 1;
    pub const FOCUS_OSC: usize = 2;
    pub const FOCUS_OUT: usize = 3;
    pub const FOCUS_OSC_A: usize = 4;
    pub const FOCUS_OSC_B: usize = 5;
    pub const FOCUS_OSC_C: usize = 6;
    pub const FOCUS_FILTER: usize = 7;
    pub const FOCUS_FILTER2: usize = 8;
    pub const FOCUS_SUB: usize = 9;
    pub const FOCUS_NOISE: usize = 10;
    pub const COUNT: usize = 11;
    pub const NAMES: [&str; COUNT] = ["master.l", "master.r", "focus.osc", "focus.out", "focus.osc.a", "focus.osc.b", "focus.osc.c", "focus.filter", "focus.filter2", "focus.sub", "focus.noise"];
}

/// Modulation sources, in matrix order.
pub mod source {
    pub const NONE: u8 = 0;
    pub const ENV_1: u8 = 1;
    pub const ENV_2: u8 = 2;
    pub const ENV_3: u8 = 3;
    pub const ENV_4: u8 = 4;
    pub const VELOCITY: u8 = 5;
    pub const NOTE: u8 = 6;
    pub const MOD_WHEEL: u8 = 7;
    pub const PITCH_BEND: u8 = 8;
    pub const AFTERTOUCH: u8 = 9;
    pub const POLY_AT: u8 = 10;
    pub const RELEASE_VEL: u8 = 11;
    pub const RAND_1: u8 = 12;
    pub const RAND_2: u8 = 13;
    pub const RAND_DISCRETE: u8 = 14;
    pub const VOICE_INDEX: u8 = 15;
    pub const VOICE_MOD_1: u8 = 16;
    pub const VOICE_MOD_2: u8 = 17;
    pub const ACTIVE_VOICES: u8 = 18;
    pub const FIXED: u8 = 19;
    pub const LFO_1: u8 = 20;
    pub const LFO_2: u8 = 21;
    pub const LFO_3: u8 = 22;
    pub const LFO_4: u8 = 23;
    pub const LFO_5: u8 = 24;
    pub const LFO_6: u8 = 25;
    pub const LFO_7: u8 = 26;
    pub const LFO_8: u8 = 27;
    pub const LFO_9: u8 = 28;
    pub const LFO_10: u8 = 29;
    pub const LFO_1_Y: u8 = 30;
    pub const LFO_2_Y: u8 = 31;
    pub const LFO_3_Y: u8 = 32;
    pub const LFO_4_Y: u8 = 33;
    pub const LFO_5_Y: u8 = 34;
    pub const LFO_6_Y: u8 = 35;
    pub const LFO_7_Y: u8 = 36;
    pub const LFO_8_Y: u8 = 37;
    pub const LFO_9_Y: u8 = 38;
    pub const LFO_10_Y: u8 = 39;
    pub const MACRO_1: u8 = 40;
    pub const MACRO_2: u8 = 41;
    pub const MACRO_3: u8 = 42;
    pub const MACRO_4: u8 = 43;
    pub const MACRO_5: u8 = 44;
    pub const MACRO_6: u8 = 45;
    pub const MACRO_7: u8 = 46;
    pub const MACRO_8: u8 = 47;
    pub const MPE_X: u8 = 48;
    pub const MPE_Y: u8 = 49;
    pub const MPE_Z: u8 = 50;
    pub const OSC_A: u8 = 51;
    pub const OSC_B: u8 = 52;
    pub const OSC_C: u8 = 53;
    pub const SUB: u8 = 54;
    pub const NOISE: u8 = 55;
    pub const FILTER_1: u8 = 56;
    pub const FILTER_2: u8 = 57;
    pub const COUNT: usize = 58;
    pub const NAMES: [&str; COUNT] = ["None", "Env 1", "Env 2", "Env 3", "Env 4", "Velocity", "Note", "Mod Wheel", "Pitch Bend", "Aftertouch", "Poly AT", "Release Vel", "Rand 1", "Rand 2", "Rand Discrete", "Voice Index", "Voice Mod 1", "Voice Mod 2", "Active Voices", "Fixed", "LFO 1", "LFO 2", "LFO 3", "LFO 4", "LFO 5", "LFO 6", "LFO 7", "LFO 8", "LFO 9", "LFO 10", "LFO 1 Y", "LFO 2 Y", "LFO 3 Y", "LFO 4 Y", "LFO 5 Y", "LFO 6 Y", "LFO 7 Y", "LFO 8 Y", "LFO 9 Y", "LFO 10 Y", "Macro 1", "Macro 2", "Macro 3", "Macro 4", "Macro 5", "Macro 6", "Macro 7", "Macro 8", "MPE X", "MPE Y", "MPE Z", "Osc A", "Osc B", "Osc C", "Sub", "Noise", "Filter 1", "Filter 2"];
}
