// @generated by tools/gen-schema.mjs from params/**/*.toml and schema/protocol.toml. Do not edit.

pub const ABI_HASH: u32 = 0xa9faee47;
pub const HEADER_BYTES: usize = 16;
pub const MAX_VOICES: usize = 32;
pub const VOICE_SLOTS: usize = 40;
pub const SUB_BLOCK: usize = 16;
pub const MAX_BLOCK: usize = 2048;
pub const CMD_CAPACITY: usize = 262144;

pub mod op {
    pub const SET_PARAM: u16 = 1;
    pub const NOTE_ON: u16 = 2;
    pub const NOTE_OFF: u16 = 3;
    pub const ALL_NOTES_OFF: u16 = 4;
    pub const ALL_SOUND_OFF: u16 = 5;
    pub const PITCH_BEND: u16 = 6;
    pub const CONTROLLER: u16 = 7;
    pub const CHANNEL_PRESSURE: u16 = 8;
    pub const POLY_PRESSURE: u16 = 9;
    pub const SET_TAPS: u16 = 16;
    pub const RESET: u16 = 17;
    pub const DEBUG: u16 = 31;
}

pub mod bytes {
    pub const SET_PARAM: usize = 8;
    pub const NOTE_ON: usize = 16;
    pub const NOTE_OFF: usize = 16;
    pub const ALL_NOTES_OFF: usize = 0;
    pub const ALL_SOUND_OFF: usize = 0;
    pub const PITCH_BEND: usize = 8;
    pub const CONTROLLER: usize = 8;
    pub const CHANNEL_PRESSURE: usize = 8;
    pub const POLY_PRESSURE: usize = 16;
    pub const SET_TAPS: usize = 8;
    pub const RESET: usize = 0;
    pub const DEBUG: usize = 8;
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Command {
    /// Set a parameter to a normalized value in 0..1.
    SetParam { id: u16, value: f32 },
    /// Start a note. noteId is chosen by the host and matched by NoteOff.
    NoteOn { note: u8, channel: u8, velocity: f32, note_id: u32 },
    /// Release a note: by noteId when it's non-zero, else by note and channel.
    NoteOff { note: u8, channel: u8, velocity: f32, note_id: u32 },
    /// Release every voice (MIDI CC 123).
    AllNotesOff,
    /// Fade every voice out within a few milliseconds (MIDI CC 120).
    AllSoundOff,
    /// Pitch wheel position, -1..1.
    PitchBend { channel: u8, value: f32 },
    /// A MIDI continuous controller, value 0..1.
    Controller { channel: u8, cc: u8, value: f32 },
    /// Channel aftertouch, 0..1.
    ChannelPressure { channel: u8, value: f32 },
    /// Per-note aftertouch, 0..1.
    PolyPressure { note: u8, channel: u8, value: f32, note_id: u32 },
    /// Choose which taps the engine records (bit i = tap i).
    SetTaps { mask: u32 },
    /// Clear all DSP state (voices, smoothers, tails) but keep parameters.
    Reset,
    /// Test hooks; see [debug].
    Debug { code: u32, arg: f32 },
}

/// Decode one payload. Returns None for unknown ops or short payloads.
pub fn decode(op: u16, p: &[u8]) -> Option<Command> {
    match op {
        op::SET_PARAM if p.len() >= 8 => Some(Command::SetParam { id: rd_u16(p, 0), value: rd_f32(p, 4) }),
        op::NOTE_ON if p.len() >= 12 => Some(Command::NoteOn { note: rd_u8(p, 0), channel: rd_u8(p, 1), velocity: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::NOTE_OFF if p.len() >= 12 => Some(Command::NoteOff { note: rd_u8(p, 0), channel: rd_u8(p, 1), velocity: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::ALL_NOTES_OFF => Some(Command::AllNotesOff),
        op::ALL_SOUND_OFF => Some(Command::AllSoundOff),
        op::PITCH_BEND if p.len() >= 8 => Some(Command::PitchBend { channel: rd_u8(p, 0), value: rd_f32(p, 4) }),
        op::CONTROLLER if p.len() >= 8 => Some(Command::Controller { channel: rd_u8(p, 0), cc: rd_u8(p, 1), value: rd_f32(p, 4) }),
        op::CHANNEL_PRESSURE if p.len() >= 8 => Some(Command::ChannelPressure { channel: rd_u8(p, 0), value: rd_f32(p, 4) }),
        op::POLY_PRESSURE if p.len() >= 12 => Some(Command::PolyPressure { note: rd_u8(p, 0), channel: rd_u8(p, 1), value: rd_f32(p, 4), note_id: rd_u32(p, 8) }),
        op::SET_TAPS if p.len() >= 4 => Some(Command::SetTaps { mask: rd_u32(p, 0) }),
        op::RESET => Some(Command::Reset),
        op::DEBUG if p.len() >= 8 => Some(Command::Debug { code: rd_u32(p, 0), arg: rd_f32(p, 4) }),
        _ => None,
    }
}

#[inline]
fn rd_u8(p: &[u8], o: usize) -> u8 {
    p[o]
}
#[inline]
fn rd_u16(p: &[u8], o: usize) -> u16 {
    let mut b = [0u8; 2];
    b.copy_from_slice(&p[o..o + 2]);
    u16::from_le_bytes(b)
}
#[inline]
fn rd_u32(p: &[u8], o: usize) -> u32 {
    let mut b = [0u8; 4];
    b.copy_from_slice(&p[o..o + 4]);
    u32::from_le_bytes(b)
}
#[inline]
fn rd_f32(p: &[u8], o: usize) -> f32 {
    let mut b = [0u8; 4];
    b.copy_from_slice(&p[o..o + 4]);
    f32::from_le_bytes(b)
}

pub mod debug {
    pub const TRAP: u32 = 1;
}

/// Telemetry slot offsets (f32 each).
pub mod tel {
    pub const VOICES_ACTIVE: usize = 0;
    pub const PEAK_L: usize = 1;
    pub const PEAK_R: usize = 2;
    pub const FOCUS_VOICE: usize = 3;
    pub const QUEUE_DROPS: usize = 4;
    pub const UNKNOWN_CMDS: usize = 5;
    pub const VOICE_NOTE: usize = 6;
    pub const VOICE_NOTE_LEN: usize = 40;
    pub const VOICE_LEVEL: usize = 46;
    pub const VOICE_LEVEL_LEN: usize = 40;
    pub const LEN: usize = 86;
}

pub mod tap {
    pub const MASTER_L: usize = 0;
    pub const MASTER_R: usize = 1;
    pub const FOCUS_OSC: usize = 2;
    pub const FOCUS_OUT: usize = 3;
    pub const COUNT: usize = 4;
    pub const NAMES: [&str; COUNT] = ["master.l", "master.r", "focus.osc", "focus.out"];
}
