// The noise oscillator's sample: generated by the tools worker for the
// chosen Noise Type and handed to the engine's sample slot 0. It's kept so a
// restarted engine gets it back straight away.

import { PARAMS, PARAM_ID } from '../gen/params';
import { tools } from '../tools/client';
import type { ParamBank } from './bank';
import { toPlain } from './param-math';

export const NOISE_SLOT = 0;

export interface SampleSink {
  loadSample(slot: number, audio: Float32Array, rate: number): void;
}

export class NoiseStore {
  private sink: SampleSink | null = null;
  private current: { index: number; data: Float32Array; rate: number } | null = null;
  private wanted = -1;
  private readonly info = PARAMS[PARAM_ID['noise.type']];

  constructor(private readonly bank: ParamBank) {
    bank.subscribe(this.info.id, () => void this.load());
  }

  attach(sink: SampleSink | null): void {
    this.sink = sink;
  }

  /** Send the sample to the engine again (after it restarted), or build it. */
  resync(): void {
    if (this.current) this.sink?.loadSample(NOISE_SLOT, this.current.data, this.current.rate);
    else void this.load();
  }

  /** Build the sample for the current Noise Type, unless it's already there. */
  async load(): Promise<void> {
    const index = toPlain(this.info, this.bank.get(this.info.id));
    if (index === this.wanted) return;
    this.wanted = index;
    const { data, rate } = await tools().call({ op: 'noise', index });
    if (this.wanted !== index) return; // a newer choice is on its way
    this.current = { index, data, rate };
    this.sink?.loadSample(NOISE_SLOT, data, rate);
  }

  /** The current sample (for display). */
  get sample(): Float32Array | null {
    return this.current?.data ?? null;
  }
}
